package br.com.instachat.emojilibrary.model;

/**
 * Created by Leonardo Assunção on 18/02/2016.
 */
public class Places {
    public static final Emoji[] DATA = new Emoji[]{
            Emoji.fromCodePoint(0x1f3e0),
            Emoji.fromCodePoint(0x1f3e1),
            Emoji.fromCodePoint(0x1f3eb),
            Emoji.fromCodePoint(0x1f3e2),
            Emoji.fromCodePoint(0x1f3e3),
            Emoji.fromCodePoint(0x1f3e5),
            Emoji.fromCodePoint(0x1f3e6),
            Emoji.fromCodePoint(0x1f3ea),
            Emoji.fromCodePoint(0x1f3e9),
            Emoji.fromCodePoint(0x1f3e8),
            Emoji.fromCodePoint(0x1f492),
            Emoji.fromChar((char) 0x26ea),
            Emoji.fromCodePoint(0x1f3ec),
            Emoji.fromCodePoint(0x1f3e4),
            Emoji.fromCodePoint(0x1f307),
            Emoji.fromCodePoint(0x1f306),
            Emoji.fromCodePoint(0x1f3ef),
            Emoji.fromCodePoint(0x1f3f0),
            Emoji.fromChar((char) 0x26fa),
            Emoji.fromCodePoint(0x1f3ed),
            Emoji.fromCodePoint(0x1f5fc),
            Emoji.fromCodePoint(0x1f5fe),
            Emoji.fromCodePoint(0x1f5fb),
            Emoji.fromCodePoint(0x1f304),
            Emoji.fromCodePoint(0x1f305),
            Emoji.fromCodePoint(0x1f303),
            Emoji.fromCodePoint(0x1f5fd),
            Emoji.fromCodePoint(0x1f309),
            Emoji.fromCodePoint(0x1f3a0),
            Emoji.fromCodePoint(0x1f3a1),
            Emoji.fromChar((char) 0x26f2),
            Emoji.fromCodePoint(0x1f3a2),
            Emoji.fromCodePoint(0x1f6a2),
            Emoji.fromChar((char) 0x26f5),
            Emoji.fromCodePoint(0x1f6a4),
            Emoji.fromCodePoint(0x1f6a3),
            Emoji.fromChar((char) 0x2693),
            Emoji.fromCodePoint(0x1f680),
            Emoji.fromChar((char) 0x2708),
            Emoji.fromCodePoint(0x1f4ba),
            Emoji.fromCodePoint(0x1f681),
            Emoji.fromCodePoint(0x1f682),
            Emoji.fromCodePoint(0x1f68a),
            Emoji.fromCodePoint(0x1f689),
            Emoji.fromCodePoint(0x1f69e),
            Emoji.fromCodePoint(0x1f686),
            Emoji.fromCodePoint(0x1f684),
            Emoji.fromCodePoint(0x1f685),
            Emoji.fromCodePoint(0x1f688),
            Emoji.fromCodePoint(0x1f687),
            Emoji.fromCodePoint(0x1f69d),
            Emoji.fromCodePoint(0x1f68b),
            Emoji.fromCodePoint(0x1f683),
            Emoji.fromCodePoint(0x1f68e),
            Emoji.fromCodePoint(0x1f68c),
            Emoji.fromCodePoint(0x1f68d),
            Emoji.fromCodePoint(0x1f699),
            Emoji.fromCodePoint(0x1f698),
            Emoji.fromCodePoint(0x1f697),
            Emoji.fromCodePoint(0x1f695),
            Emoji.fromCodePoint(0x1f696),
            Emoji.fromCodePoint(0x1f69b),
            Emoji.fromCodePoint(0x1f69a),
            Emoji.fromCodePoint(0x1f6a8),
            Emoji.fromCodePoint(0x1f693),
            Emoji.fromCodePoint(0x1f694),
            Emoji.fromCodePoint(0x1f692),
            Emoji.fromCodePoint(0x1f691),
            Emoji.fromCodePoint(0x1f690),
            Emoji.fromCodePoint(0x1f6b2),
            Emoji.fromCodePoint(0x1f6a1),
            Emoji.fromCodePoint(0x1f69f),
            Emoji.fromCodePoint(0x1f6a0),
            Emoji.fromCodePoint(0x1f69c),
            Emoji.fromCodePoint(0x1f488),
            Emoji.fromCodePoint(0x1f68f),
            Emoji.fromCodePoint(0x1f3ab),
            Emoji.fromCodePoint(0x1f6a6),
            Emoji.fromCodePoint(0x1f6a5),
            Emoji.fromChar((char) 0x26a0),
            Emoji.fromCodePoint(0x1f6a7),
            Emoji.fromCodePoint(0x1f530),
            Emoji.fromChar((char) 0x26fd),
            Emoji.fromCodePoint(0x1f3ee),
            Emoji.fromCodePoint(0x1f3b0),
            Emoji.fromChar((char) 0x2668),
            Emoji.fromCodePoint(0x1f5ff),
            Emoji.fromCodePoint(0x1f3aa),
            Emoji.fromCodePoint(0x1f3ad),
            Emoji.fromCodePoint(0x1f4cd),
            Emoji.fromCodePoint(0x1f6a9),
            Emoji.fromString("\ud83c\uddef\ud83c\uddf5"),
            Emoji.fromString("\ud83c\uddf0\ud83c\uddf7"),
            Emoji.fromString("\ud83c\udde9\ud83c\uddea"),
            Emoji.fromString("\ud83c\udde8\ud83c\uddf3"),
            Emoji.fromString("\ud83c\uddfa\ud83c\uddf8"),
            Emoji.fromString("\ud83c\uddeb\ud83c\uddf7"),
            Emoji.fromString("\ud83c\uddea\ud83c\uddf8"),
            Emoji.fromString("\ud83c\uddee\ud83c\uddf9"),
            Emoji.fromString("\ud83c\uddf7\ud83c\uddfa"),
            Emoji.fromString("\ud83c\uddec\ud83c\udde7"),
    };
}

